---
name: Push
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/inko:latest
    steps:
      - run: microdnf install --quiet --assumeyes tar git
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: inko --version
      - run: inko fmt --check

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/inko:latest
    steps:
      - run: microdnf install --quiet --assumeyes tar git
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        id: test
        with:
          path: '~/.local/share/inko/packages'
          key: test-${{ hashFiles('inko.pkg') }}
      - run: inko --version
      - run: inko pkg sync
      - run: inko test
